<?php

function notify($to,$data){

    $api_key="AAAAvaxaZBI:APA91bFIqn723wmyXXBfbRHQ089WfOH1kCtHiwb58XZ0b1maZC42aG61cb8YFv2kPZ_TVQ7VAfqYmhqyZ7kNOLap_jYCHMX5M1mdMosT9-w0zTjQKLd6y8IZ98fMLQmKTCmWcb_fKvlo";
    $url="https://fcm.googleapis.com/fcm/send";
    $fields=json_encode(array('to'=>$to,'data'=>$data));

    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));

    $headers = array();
    $headers[] = 'Authorization: key ='.$api_key;
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
}

 //if($_POST['driverID']){
	 $data = json_decode(file_get_contents('php://input'), true);
	 //print_r($data);
     //$driverID = $data['driverID'];
	 
	 //$to="dBkxmIyzADk:APA91bGUl0aEdv2Jr83UbPQuNLPmbjlOKUcHxorX3_2Y_3sT3fdjnRIObOiuuQ3ZKOEiFrjYu_AI5Cj5wBJSUWc4rBn6U1h0D4ZuqVmcPU1Bgav02h39ii-9Seucl7F30dESiwnsX0M3";
	 $to="eSk4WK2bPzI:APA91bE2umq01tmLT_Bt8fEuvtuGN8PqtS1jvvic9-Pq0pHGGfGU_cZI6PL3Fwph6jYK7SZPxbLYk08FPBJbDVrHS4YdTFl_Tf8tnJ-psax8radp6aMZPBo-kqOIzJLy68ll8tcnWEXq";
		
	$data=array(
		'title'=>'Driver',
		'message'=>'Vous avez un nouveau client. From PHP',
		'lat'=>36.216755,
		'lng'=>2.747962
	);

	notify($to,$data);
	//echo "Notification Sent";
 
// }
 
//LG ...
//$to="eSk4WK2bPzI:APA91bE2umq01tmLT_Bt8fEuvtuGN8PqtS1jvvic9-Pq0pHGGfGU_cZI6PL3Fwph6jYK7SZPxbLYk08FPBJbDVrHS4YdTFl_Tf8tnJ-psax8radp6aMZPBo-kqOIzJLy68ll8tcnWEXq";

//$to="dBkxmIyzADk:APA91bGUl0aEdv2Jr83UbPQuNLPmbjlOKUcHxorX3_2Y_3sT3fdjnRIObOiuuQ3ZKOEiFrjYu_AI5Cj5wBJSUWc4rBn6U1h0D4ZuqVmcPU1Bgav02h39ii-9Seucl7F30dESiwnsX0M3";
/*$data=array(
    'title'=>'Greetings',
    'body'=>'Hi, From PHP Script'
);

notify($to,$data);
echo "Notification Sent";
*/
?>