# Generated by Django 3.2.12 on 2022-06-19 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='long',
            new_name='log',
        ),
        migrations.AddField(
            model_name='user',
            name='point_actuelle',
            field=models.ForeignKey(db_column='point', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.point'),
        ),
    ]
