# Generated by Django 3.2.12 on 2022-06-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220619_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='occupe',
            field=models.BooleanField(default=False),
        ),
    ]
