# Generated by Django 3.2.12 on 2022-06-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_voiture_occupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursa',
            name='date_arrive',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursa',
            name='date_dapart',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
