# Generated by Django 3.2.12 on 2022-06-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220621_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='matrciule',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
