# Generated by Django 3.2.12 on 2022-06-22 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tracking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
