# Generated by Django 3.2.12 on 2022-06-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_tracking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firebaseID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
